
var optionTexts = {
    option1: [
        "The Government's new plans will be made by a regulator who is not accountable to the public and cannot be scrutinised. It is concerning that a body who will have a significant impact on our rights to freedom of expression will not subject to democratic checks and balances.",
        "The Government's latest proposals will be devised by an unaccountable regulator, impervious to public scrutiny. The fact that this entity, which holds sway over our freedom of expression, will operate without democratic checks and balances presents a significant risk of abuse.",
        "The Government's upcoming initiative to curtail free speech will be formulated by an unaccountable regulator, immune to public scrutiny and devoid of democratic oversight. This raises concerns regarding the potential ramifications on our vital right to freedom of expression.",
        "The Government's recently announced plans to introduce online censorship will be determined by an unaccountable regulatory body, evading public scrutiny and without democratic checks and balances. It is disconcerting to think that an entity with such influence over our freedom of expression will operate without appropriate democratic safeguards.",
        "The Government's proposed internet censorship measures will be shaped by a regulator who lacks accountability to the public and remains beyond the scope of scrutiny. The absence of democratic checks and balances for an entity that wields significant power over our freedom of expression is cause for concern.",
        "The Government's forthcoming legislation will grant power to an unelected regulator, shielded from public scrutiny and unimpeded by democratic checks and balances. This raises red flags about the potential implications on our fundamental rights to freedom of expression as there will be no recourse for society to pursue accountability.",
        "The Government's latest plans to police what people can say online would be implemented by a regulator who is unaccountable to the public and immune to scrutiny. It is troubling that an entity wielding considerable influence over our freedom of expression will operate without democratic checks and balances.",
        "The Government's newly proposed restrictions on free speech would be formulated and policed by a regulator who is unaccountable to the public and evades scrutiny. The absence of democratic checks and balances for an entity that will significantly impact our rights to freedom of expression is seriously concerning."
    ],
    option2: [
        "It is abundantly clear that these codes of practice will be effective hate-speech and misinformation laws for the internet and media. The proposals describe content as unsafe “if it discriminates against an ethnic group, or interferes in democratic processes. These forms of harm also fall within our proposals.” However, it does not clarify what it means by content that “interferes in democratic process”. The reach of these regulations would be far greater than the previously proposed hate speech laws, and their enforcement and effect would be far greater. By having an independent regulator determine whether platforms and publishers are upholding their obligations under codes of practice, the regulator will inevitably have to decide what is hate speech and misinformation. Having a government entity make such decisions, particularly when they pertain to speech rights, is undemocratic and harmful to the public trust in the Government and the media they consume.",
        "These codes of practice would serve as an equivalent to legislation against hate speech and misinformation in the realm of internet and media. However, the impact of these regulations would extend well beyond the proposed hate speech laws, resulting in more extensive enforcement and effects. By entrusting an independent regulator with the responsibility to assess platform and publisher compliance with the codes of practice, the regulator will inevitably be tasked with determining what constitutes hate speech and misinformation. There is aalso a lack of clarity regarding the precise meaning of content that \"interferes in democratic processes.\" Allowing a government entity to make such decisions, especially in matters involving speech rights, is undemocratic and undermines public trust in the Government and the media they consume. ",
        "The implication of these codes of practice as comprehensive hate speech and misinformation laws for the internet and media is abundantly clear. The proposals explicitly identify content as “unsafe” if it discriminates against an ethnic group or interferes with democratic processes, both falling within the scope of those earlier proposed hate speech laws. However, the definition of content that \"interferes in democratic processes\" is ambiguous and open to many interpretations. The impact of these regulations would far surpass that of the proposed hate speech laws, resulting in more extensive enforcement and ramifications. By delegating the responsibility of assessing platform and publisher compliance with the codes of practice to an independent regulator, the inevitable task of determining what constitutes hate speech and misinformation falls upon them. Allowing a government entity to make such decisions, particularly when they involve speech rights, is undemocratic and detrimental to public trust in the Government and the media they engage with.",
        "It is evident beyond doubt that these codes of practice will serve as effective legislation against hate speech and misinformation in the digital and media domains. The precise meaning of content that \"interferes in democratic processes\" is unclear. The reach of these regulations would extend well beyond the proposed hate speech laws, resulting in broader enforcement and impact. By entrusting an independent regulator with the responsibility to assess whether platforms and publishers comply with the codes of practice, the regulator will inevitably face the task of determining what qualifies as hate speech and misinformation. Allowing an unelected entity to make such decisions, particularly when they pertain to speech rights, is undemocratic and undermines public trust in the Government and the media they consume.",
        "These codes of practice leave no room for doubt that they will effectively serve as hate speech and misinformation laws for the internet and media. The specific definition of content that \"interferes in democratic processes\" is unspecified. The impact of these regulations would extend far beyond the proposed hate speech laws, leading to broader enforcement and consequences. By assigning the responsibility of assessing platform and publisher compliance with the codes of practice to an independent regulator, the regulator will inevitably have to determine what constitutes hate speech and misinformation. Allowing an unaccountable entity to make such decisions, particularly in matters involving speech rights, is undemocratic and undermines public trust in the Government and the media they consume.",
        "The reality that these codes of practice are robust hate speech and misinformation laws for the internet and media is abundantly clear. The specific interpretation of content that \"interferes in democratic processes\" remains unclear. The reach of these regulations would go well beyond the proposed hate speech laws, resulting in broader enforcement and impact. By entrusting an independent regulator with the responsibility of assessing platform and publisher compliance with the codes of practice, the regulator will inevitably be tasked with determining what constitutes hate speech and misinformation. Allowing a government-appointed entity to make such decisions, particularly when they involve speech rights, is undemocratic and undermines public trust in the Government and the media they consume.",
        "These codes of practice leave no room for doubt that they will serve as effective laws against hate speech and misinformation in the realm of internet and media. The exact definition of content that \"interferes in democratic processes\" is unclear. The impact of these regulations would extend far beyond the proposed hate speech laws, resulting in more extensive enforcement and effects. By assigning an independent regulator with the responsibility to assess platform and publisher compliance with the codes of practice, the regulator will inevitably be faced with determining what qualifies as hate speech and misinformation. Allowing a government-selected entity to make such decisions, particularly in matters involving speech rights, is undemocratic and harmful to public trust in the Government and the media they consume.",
        "That these codes of practice are robust hate speech and misinformation laws for the internet and media is abundantly clear. The precise interpretation of content that \"interferes in democratic processe\" is yet to be clarified. The reach of these regulations would exceed that of the proposed hate speech laws, resulting in broader enforcement and impact. By entrusting an independent regulator with the responsibility of assessing platform and publisher compliance with the codes of practice, the regulator will inevitably have to decide what constitutes hate speech and misinformation. Allowing a unelected entity to make such decisions, particularly when they pertain to speech rights, is undemocratic and harmful to public trust in the Government and the media they consume."
    ],
    option3: [
        "In determining whether platforms and publishers are meeting expectations of their codes of practice, the proposed \"regulator\" will have to play the role of a 'Ministry of Truth'. This Orwellian over-reach could see digital platforms forced to cancel legal speech which is disliked by those with social and cultural power. The proposals are dangerously vague and unworkable. What content will be regulated is unclear, and the Regulator will not be able to enforce the Codes to International platforms.",
        "The proposed \"regulator\" tasked with assessing platform and publisher compliance with codes of practice would effectively become a 'Ministry of Truth'. This Orwellian expansion of Government interference on free speech could potentially lead to the suppression of legally protected speech that goes against cultural sentiments of those with decision-making power. The vagueness and impracticality of the proposals pose a significant danger. The specific content that will be subjected to regulation remains unclear, and the regulator will lack the authority to enforce the codes on international platforms.",
        "The described role of the proposed \"regulator\" in evaluating platform and publisher adherence to codes of practice elucidates reasonable concerns about the emergence of a modern-day 'Ministry of Truth'. This Orwellian encroachment could result in the restriction of lawful speech simply due to cultural disapproval by those tasked with policing. The proposals themselves are alarmingly vague and unfeasible. The exact scope of regulated content remains unclear, and the regulator's jurisdiction over international platforms is limited.",
        "The proposed \"regulato\" would assume the mantle of a 'Ministry of Truth' in assessing whether platforms and publishers meet the expectations set by codes of practice. This Orwellian expansion of authority poses the risk of censoring lawful speech that may be culturally unpopular with those with influence over the decisions made by the regulator. The proposals themselves suffer from dangerous ambiguity and impracticality. The specific content subject to regulation remains unclear, and the regulator lacks jurisdiction over enforcing the codes on international platforms.",
        "By assigning the role of a 'Ministry of Truth' to the proposed \"regulator,\" the evaluation of platform and publisher compliance with codes of practice takes a concerning turn. This Orwellian overreach threatens the potential cancellation of legal speech based on cultural disapproval from powerful and influential forces. The vagueness and unfeasibility of the proposals are evident, as it remains unclear which content will fall under regulation, and the regulator lacks the authority to enforce the codes on international platforms.",
        "6.	The proposed \"regulator\" would assume the onerous responsibility of a 'Ministry of Truth' in assessing the adherence of platforms and publishers to codes of practice. This Orwellian extension of authority raises the spectre of digital platforms being compelled to censor lawful speech that is deemed culturally unfavourable in the eyes of those entrusted with regulating. The proposals themselves suffer from dangerous imprecision and impracticality. The specific content to be regulated remains uncertain, and the regulator's jurisdiction over international platforms is limited.",
        "The proposed \"regulator\" would be thrust into the role of a 'Ministry of Truth' when it comes to determining platform and publisher compliance with codes of practice. This Orwellian expansion of power has the potential to force digital platforms to suppress legal speech that clashes with the cultural preferences of those with power within the system. The proposals themselves are fraught with dangerous ambiguity and impracticality. The precise content subject to regulation remains unclear, and the regulator lacks the ability to enforce the codes on international platforms.",
        "In the assessment of platform and publisher compliance with codes of practice, the proposed \"regulator\" would effectively become a contemporary 'Ministry of Truth'. This Orwellian overreach could lead to the suppression of lawful speech that faces cultural disapproval from those with social and cultural power. The proposals suffer from dangerous vagueness and impracticality. The exact nature of regulated content remains unclear, and the regulator lacks the jurisdiction to enforce the codes on international platforms."
    ],
    option4: [
        "Censoring the internet is a fool's errand, and the codes of practice will be unlikely to succeed in reducing harm while still suppressing legitimate speech. It is not clear if these changes will reduce ‘harm’, or whether they will simply narrow the scope of public discourse. Social media moderation is notorious for inconsistent enforcement and wide reach on the basis of subjective terminology. Despite this, the proposed regulations envision complicated censorship of online content with firm enforcement. This will be likely to result in certain types of content being censored with a broad-brush. The proposals also envisage the use of AI technology in the moderation of user-generated content. AI has a notorious reputation on social media already for censoring legitimate content, creating sweeping online practices to avoid the AI moderation. An example is the frequent use of the term “unalived” online to avoid filters targeting words such as “killed’ or “murdered”. With the special emphasis placed on protecting minors from potentially harmful content it can be expected that such automatic filters will be extensive and complicated, yet ineffective",
        "Attempting to censor the internet is a futile endeavour, and the codes of practice are unlikely to achieve their goal of reducing harm while simultaneously stifling legitimate speech. The impact of these changes on actually minimising 'harm' remains unclear, and there is a risk that they may merely narrow the scope of public discussion. Social media moderation is known for its inconsistent enforcement and subjective interpretation of terms, leading to a wide-reaching impact. Nevertheless, the proposed regulations propose complex censorship of online content with stringent enforcement, potentially resulting in the broad censorship of certain types of content.",
        "Engaging in internet censorship is an impractical pursuit, and the proposed codes of practice are unlikely to effectively mitigate harm while simultaneously suppressing legitimate speech. It remains unclear whether these changes will genuinely reduce 'harm' or merely limit the parameters of acceptable discourse. The history of social media moderation is marked by inconsistent enforcement and the extensive reach of subjective terms. Despite this, the proposed regulations aim for intricate censorship of online content with rigorous enforcement, which may inadvertently result in the blanket censorship of specific content.",
        "The act of censoring the internet is a fruitless endeavour, and the implementation of codes of practice is unlikely to successfully minimise harm while stifling legitimate speech. The actual impact of these changes on harm reduction is ambiguous, and there is a risk that they will narrow the realm of public discourse rather than achieve their intended goals. Social media moderation is notorious for its inconsistent enforcement and the wide-ranging effects based on subjective language. Nevertheless, the proposed regulations envision complex censorship of online content with strict enforcement, which is likely to lead to the broad censorship of certain content types.",
        "Pursuing internet censorship is an endeavour destined to fail, and the proposed codes of practice are unlikely to effectively reduce harm while simultaneously suppressing legitimate speech. The extent to which these changes will truly mitigate harm is uncertain and difficult to quantify, and there is a possibility that they will merely restrict public discourse. Social media moderation is infamous for its inconsistent enforcement and the far-reaching implications of subjective terminology. Nevertheless, the proposed regulations envision intricate censorship of online content with robust enforcement, which may ultimately result in the broad-scale censorship of specific content.",
        "Censoring the internet is a futile project, and the implementation of codes of practice is unlikely to succeed in effectively reducing harm while suppressing legitimate speech. It is unclear whether these changes will genuinely diminish 'harm' or simply limit the scope of public discourse. Social media moderation is notorious for its inconsistent enforcement and the broad impact of subjective terminology. Despite this, the proposed regulations propose complex censorship of online content with stringent enforcement, potentially leading to the broad censorship of certain types of content.",
        "Engaging in internet censorship is an exercise in futility, and the proposed codes of practice are unlikely to achieve their intended purpose of reducing harm while simultaneously stifling legitimate speech. The actual effectiveness of these changes in harm reduction is uncertain, and there is a possibility that they may only narrow the range of public discourse. Social media moderation is renowned for its inconsistent enforcement and the extensive reach of subjective terms. Nonetheless, the proposed regulations envisage intricate censorship of online content with rigorous enforcement, which could result in the censorship of certain content categories.",
        "Attempting to censor the internet is an impossible and foolish task, and the codes of practice are unlikely to succeed in effectively mitigating harm while simultaneously suppressing legitimate speech. The actual impact of these changes on harm reduction is unclear, and there is a risk that they will merely restrict the scope of public discourse. Social media moderation is infamous for its inconsistent enforcement and the wide-ranging consequences based on subjective language. Nevertheless, the proposed regulations propose complex censorship of online content with firm enforcement, which may ultimately lead to the broad censorship of specific content."
    ],
    option5: [
        "The proposals envisage that the codes of practice will be developed by the regulator in conjunction with industry members (but without democratic oversight). Inevitably these industry members who will work with the regulator to develop the codes will be the largest and most well-established members of their respective sectors. Nonetheless, the codes of practice they develop will apply to all members in their industry sectors, regardless of whether other industry members were able to give input into the codes or consented to the requirements of the codes. This creates an unacceptable risk of regulatory capture. \n The proposals are in effect inviting established players in media and online spaces to create the rules that their competitors will have to abide by. This will in all likelihood be used to suppress and muscle-out competition, particularly from smaller and newer media platforms.",
        "According to the proposals, the regulator will collaborate with industry members to develop the codes of practice, without democratic oversight. Inevitably, these industry members involved in the code development process will be the largest and most influential players within their respective sectors. Nevertheless, the codes of practice they create will be applicable to all members in their industry sectors, regardless of whether other industry members had the opportunity to contribute or consent to the code requirements.\n This scenario presents an unacceptable risk of regulatory capture. Effectively, the proposals invite established players in media and online spaces to shape the rules that their competitors must adhere to. This arrangement is likely to be utilised to suppress and marginalise competition, particularly from smaller and newer media platforms.",
        "As per the proposals, the regulator will collaborate with industry members, without democratic oversight, to develop the codes of practice. Inevitably, these industry members involved in the development process will predominantly consist of the largest and most influential entities within their respective sectors. However, the resulting codes of practice will be applicable to all members within their industry sectors, irrespective of whether other industry members had the chance to provide input or consent to the code requirements.\n This situation introduces an unacceptable risk of regulatory capture. Essentially, the proposals invite established players in media and online spaces to shape the regulations that their competitors must comply with. This is likely to be exploited as a means to suppress and eliminate competition, especially from smaller and newer media platforms.",
        "The proposals envision that the regulator, in collaboration with industry members but without democratic oversight, will develop the codes of practice. Inevitably, the industry members participating in this process will primarily comprise the largest and most influential entities within their respective sectors. Nonetheless, the resulting codes of practice will be binding upon all members in their industry sectors, regardless of whether other industry members had the opportunity to contribute or consent to the code requirements.\n This arrangement presents an unacceptable risk of regulatory capture. Essentially, the proposals invite established players in media and online spaces to establish the rules that their competitors must adhere to. This dynamic is likely to be exploited to suppress and marginalize competition, particularly smaller and newer media platforms.",
        "According to the proposals, the regulator will collaborate with industry members, without democratic oversight, to develop the codes of practice. Inevitably, the industry members involved in this process will predominantly consist of the largest and most influential players within their respective sectors. Nevertheless, the codes of practice they create will apply to all members in their industry sectors, regardless of whether other industry members had the opportunity to contribute or consent to the code requirements.\n This poses an unacceptable risk of regulatory capture. In essence, the proposals invite established players in media and online spaces to shape the rules that their competitors must abide by. This is likely to be exploited as a means to suppress and eliminate competition, particularly smaller and newer media platforms.",
        "The proposals outline that the regulator will collaborate with industry members, without democratic oversight, to develop the codes of practice. Inevitably, the industry members involved in this process will primarily consist of the largest and most influential entities within their respective sectors. However, the resulting codes of practice will be applicable to all members within their industry sectors, irrespective of whether other industry members had the opportunity to contribute or consent to the code requirements.\n This setup creates an unacceptable risk of regulatory capture. Essentially, the proposals invite established players in media and online spaces to shape the regulations that their competitors must comply with. This is likely to be exploited to suppress and marginalize competition, particularly smaller and newer media platforms.",
        "As outlined in the proposals, the regulator will collaborate with industry members, without democratic oversight, to develop the codes of practice. Naturally, the industry members involved in this process will largely consist of the largest and most well-established players within their respective sectors. However, the resulting codes of practice will be applicable to all members within their industry sectors, regardless of whether other industry members had the opportunity to contribute or consent to the code requirements.\n This arrangement poses an unacceptable risk of regulatory capture. Effectively, the proposals invite established players in media and online spaces to shape the rules that their competitors must adhere to. This is likely to be exploited as a means to suppress and marginalize competition, particularly smaller and newer media platforms.",
        "The proposals indicate that the regulator will collaborate with industry members, without democratic oversight, to develop the codes of practice. Inevitably, the industry members involved in this process will predominantly consist of the largest and most influential entities within their respective sectors. Nonetheless, the resulting codes of practice will be imposed upon all members in their industry sectors, irrespective of whether other industry members had the opportunity to provide input or consent to the code requirements.\n This scenario presents an unacceptable risk of regulatory capture. Essentially, the proposals invite established players in media and online spaces to shape the regulations that their competitors must comply with. This is likely to be utilised to suppress and eliminate competition, particularly smaller and newer media platforms."
    ],
    option6: [
        "The compliance requirements of the regulations are complicated and extensive, and the proposals anticipate that “platforms will need to undertake significant work as part of the wider tech industry” to uphold their proposed obligations. These oppressive requirements would likely create significant costs for platforms operating in New Zealand. It is likely the only platforms with the resources to comply with these costs would be the largest in the space, reducing competition and creating barriers of entry into the media space. Enforcing codes and regulations regarding social media and other internet platforms, will be very difficult when it comes to major international players, and so it is likely that enforcement mechanisms would be most easily turned on New Zealand based platforms. This would strangle local media platforms and significantly reduce diversity and competition in New Zealand's media space.",
        "The regulations impose complex and extensive compliance requirements, with the proposals acknowledging that platforms will need to undertake substantial efforts, alongside the wider tech industry, to meet the proposed obligations. These burdensome requirements are likely to result in significant costs for platforms operating in New Zealand. It is probable that only the largest platforms with substantial resources would be able to bear these significant costs, thus reducing competition and erecting barriers to entry in the media landscape. In particular, enforcing the codes against international actors, especially on social media and other internet platforms, presents massive challenges, with it much easier to target and apply enforcement mechanisms to New Zealand-based platforms. This scenario would suffocate local media platforms and severely diminish diversity and competition in New Zealand's media sphere.",
        "The regulations include intricate and extensive compliance requirements, with the proposals expecting platforms to undertake substantial work, alongside the wider tech industry, to fulfil their proposed obligations. These demanding requirements are likely to impose significant costs on platforms operating in New Zealand. It is foreseeable that only the largest platforms with ample resources would be able to wear these costs, thereby diminishing competition and establishing barriers to entry in the media sector. Specifically regarding social media and other internet platforms, enforcing the codes against international actors would be challenging, leading to the likelihood of enforcement mechanisms being primarily directed towards New Zealand-based platforms. Consequently, this would stifle local media platforms and drastically reduce diversity and competition within New Zealand's media landscape.",
        "The regulations introduce complex and extensive compliance requirements, with the proposals anticipating that platforms will need to undertake substantial efforts, alongside the broader tech industry, to fulfill their proposed obligations. These onerous requirements are likely to generate significant costs for platforms operating in New Zealand. It is probable that only the largest platforms with abundant resources would be capable of meeting these costs, thereby diminishing competition and erecting barriers to entry in the media sphere. Particularly concerning social media and other internet platforms, enforcing the codes against international actors would present challenges, implying that enforcement mechanisms would be more easily directed at New Zealand-based platforms. This would strangle local media platforms and substantially reduce diversity and competition within New Zealand's media landscape.",
        "The regulations impose intricate and extensive compliance requirements, as the proposals acknowledge that platforms will need to undertake significant efforts, in conjunction with the wider tech industry, to uphold their proposed obligations. These burdensome requirements are likely to result in substantial costs for platforms operating in New Zealand. It is likely that only the largest platforms with ample resources would be able to bear these costs, thereby reducing competition and creating entry barriers in the media space. Particularly in the case of social media and other internet platforms, enforcing the codes against international actors would pose difficulties, making it more convenient to apply enforcement mechanisms against New Zealand-based platforms. This would stifle local media platforms and significantly diminish diversity and competition within New Zealand's media landscape.",
        "The regulations establish complex and extensive compliance requirements, with the proposals recognizing that platforms will need to undertake significant work, alongside the wider tech industry, to meet their proposed obligations. These demanding requirements are likely to entail substantial costs for platforms operating in New Zealand. It is expected that only the largest platforms with significant disposable resources would be capable of complying with these costs, thereby reducing competition and erecting barriers to entry in the media sphere. Especially in the realm of social media and other internet platforms, enforcing the codes against international actors would prove challenging, making it easier to direct enforcement mechanisms towards New Zealand-based platforms. Consequently, this would hinder local media platforms and greatly diminish diversity and competition in New Zealand's media landscape.",
        "The regulations introduce complex and extensive compliance requirements, with the proposals anticipating that platforms will need to undertake significant efforts, alongside the wider tech industry, to fulfill their proposed obligations. These onerous requirements are likely to result in substantial costs for platforms operating in New Zealand. It is foreseeable that only the largest platforms with ample resources would be able to bear these costs, thereby reducing competition and creating barriers to entry in the media sector. Particularly concerning social media and other internet platforms, enforcing the codes against international actors would present challenges, suggesting that enforcement mechanisms would most easily target New Zealand-based platforms. This would strangle local media platforms and significantly diminish diversity and competition within New Zealand's media landscape.",
        "The regulations entail intricate and extensive compliance requirements, with the proposals acknowledging that platforms will need to undertake significant work, alongside the broader tech industry, to meet their proposed obligations. These burdensome requirements are likely to result in substantial costs for platforms operating in New Zealand. It is likely that only the largest platforms with ample resources would be capable of meeting these costs, thereby diminishing competition and creating barriers to entry in the media space. Particularly with social media and other internet platforms, enforcing the codes against international actors would be difficult, making it likely that enforcement mechanisms would be most easily directed at New Zealand-based platforms. This would strangle local media platforms and significantly reduce diversity and competition in New Zealand's media space."
    ],
    option7: [
        "The proposed regulatory scheme aims to reduce harm by limiting the kinds of content that can be hosted on online and media platforms, but like hate speech laws it fails to address the underlying issues. No person has their mind changed by being censored, but an open media and internet allows for even the difficult discussions to happen, and ensures that education and counter-speech can be used to combat bad ideas.",
        "The proposed regulatory scheme intends to mitigate harm by imposing restrictions on the content that online and media platforms can host. However, similar to hate speech laws, it overlooks the fundamental issues at hand. Censorship does not change people's minds; instead, an open media and internet foster the necessary environment for challenging discussions to take place. It ensures that education and counter-speech can be employed to combat misguided ideas",
        "The objective of the proposed regulatory scheme is to reduce harm by imposing limitations on the types of content allowed on online and media platforms. However, akin to hate speech laws, it fails to address the underlying root causes. Censorship does not lead to changes in perspectives. On the other hand, an open media and internet provide a platform for difficult discussions to transpire, enabling education and counter-speech as effective tools against detrimental ideas.",
        "The proposed regulatory scheme aims to minimize harm by imposing restrictions on the content permitted on online and media platforms. However, like hate speech laws, it neglects to tackle the underlying issues. Censorship does not result in changed minds. Conversely, an open media and internet foster an environment where challenging discussions can take place, facilitating the use of education and counter-speech to combat flawed ideas.",
        "With the goal of reducing harm, the proposed regulatory scheme seeks to impose limitations on the content hosted on online and media platforms. However, similar to hate speech laws, it overlooks the underlying concerns. Censorship does not lead to mindset changes. Conversely, an open media and internet create opportunities for even difficult discussions to occur, allowing education and counter-speech to serve as effective means of combating misguided notions.",
        "The proposed regulatory scheme intends to mitigate harm by imposing constraints on the content that can be featured on online and media platforms. However, like hate speech laws, it fails to address the root issues. Censorship does not result in changed perspectives. Instead, an open media and internet foster an environment where even challenging discussions can transpire, enabling education and counter-speech to effectively combat flawed ideas.",
        "The objective of the proposed regulatory scheme is to minimize harm by restricting the types of content permissible on online and media platforms. However, akin to hate speech laws, it does not tackle the underlying concerns. Censorship does not bring about a change in beliefs. Conversely, an open media and internet facilitate the occurrence of even difficult discussions, allowing education and counter-speech to be employed as tools to combat misguided ideas.",
        "The proposed regulatory scheme aims to reduce harm by imposing limitations on the content that can be hosted on online and media platforms. However, like hate speech laws, it overlooks the underlying issues. Censorship does not lead to a change in mindset. Conversely, an open media and internet provide a platform for even challenging discussions to take place, ensuring that education and counter-speech can be utilized to combat misguided ideas."
    ]
};

function getSelectedOptions() {
    var form = document.getElementById("checkbox-form");
    var checkboxes = form.querySelectorAll('input[name="option"]:checked');
    var selectedOptions = [];

    checkboxes.forEach(function (checkbox) {
        selectedOptions.push(checkbox.value);
    });

    if (selectedOptions.length === 0) {
        var alertElement = document.getElementById("alert");
        alertElement.textContent = "Please select at least one option.";
        return;
    }

    var alertElement = document.getElementById("alert");
    alertElement.textContent = "";

    var resultElement = document.getElementById("result");
    resultElement.value = "";

    selectedOptions.forEach(function (option) {
        var paragraphs = optionTexts[option];
        if (paragraphs) {
            var randomIndex = Math.floor(Math.random() * paragraphs.length);
            var paragraph = paragraphs[randomIndex];
            resultElement.value += paragraph + "\n\n";
        }
    });

    checkboxes.forEach(function (checkbox) {
        checkbox.checked = false;
    });
}

function scrollToElement(elementId) {
    var targetElement = document.getElementById(elementId);

    if (targetElement) {
        targetElement.scrollIntoView({ behavior: 'smooth' });
    }
}

function appendRandomParagraph() {
    var paragraphs = [
        "I implore you to consider the negative impacts that could arise from this proposal and scrap these plans.",
        "I urge you to take into account the potential adverse consequences that may result from this proposal and abandon these plans.",
        "Please carefully consider the detrimental effects that could arise from this proposal and discard these plans.",
        "I strongly encourage you to reflect on the negative impacts that may arise from this proposal and reconsider and abandon these plans.",
        "Please step back and consider the potential adverse outcomes that could stem from this proposal and completely discard these plans.",
        "I urge you to seriously consider the detrimental consequences that may arise from this proposal and halt these plans.",
        "It is crucial that you reflect on the negative impacts that could result from this proposal and make the decision to scrap these plans.",
        "It is imperative that you carefully assess the potential adverse effects that could arise from this proposal and make the wise choice to abandon these plans.",
    ];

    var randomIndex = Math.floor(Math.random() * paragraphs.length);
    var randomParagraph = paragraphs[randomIndex];

    var textarea = document.getElementById("result");
    textarea.value += randomParagraph + "\n";
}

function callMultipleFunctions() {
    var form = document.getElementById("checkbox-form");
    var checkboxes = form.querySelectorAll('input[name="option"]:checked');

    if (checkboxes.length === 0) {
        var alertElement = document.getElementById("alert");
        alertElement.textContent = "Please select at least one option.";
        return; // Stop the function if no options are selected
    }

    getSelectedOptions();
    scrollToElement('targetElement');
    appendRandomParagraph();

}
